### ISSUE TITLE
Docs unclear

### ISSUE THREAD

**Issue by adamzerner** [rschristian/react-preact-lib#1]
I am confused about how to use this library, and I expect that others would be as well. So then, it seems worth elaborating and clarifying in the README.

In the "Usage" section it says to run `yarn && yarn build` and that doing so will generate those directories. However, what if you don't have `yarn` (I don't)? And what I'd assume that there is more to do than just run that command.

I came across https://documentation.divio.com/ recently. I think it's a great resource on how to write documentation that you might like as well.

**Comment by rschristian** [comment]
> However, what if you don't have yarn (I don't)?

Just swap in NPM, PNPM, or your package manager of choice. It makes no difference.

```
$ npm install && npm run build
```

> And what I'd assume that there is more to do than just run that command.

Nope, that's it for building this demo.

**Comment by adamzerner** [comment]
> Just swap in NPM, PNPM, or your package manager of choice. It makes no difference.

Hm. Personally I'm using Deno's [Fresh](https://fresh.deno.dev/) web framework. What would I do there?

> Nope, that's it for building this demo.

I guess this assumes that you have`react-preact-lib` in `package.json` and something about the build script in `package.json`, right? Is there anything else that it assumes, such as your directory structure?

**Comment by rschristian** [comment]
> What would I do there?

No clue, I don't use Deno. I'm sure there's plenty of resources online though.

> I guess this assumes that you havereact-preact-lib in package.json and something about the build script in package.json, right?

No. You build the lib locally, publish to NPM, and then consume it by adding `<insert-lib-name-here>` to the consuming application's `package.json`.

Might help to read up on the basics of NPM.

> Is there anything else that it assumes, such as your directory structure?

Microbundle uses the `package.json#source` key (if provided) to determine entry point, else falls back into `src/index.*` I believe. [Microbundle's docs](https://github.com/developit/microbundle)

**Comment by rschristian** [comment]
Closing this out, as there's no issue specifically with this repo.

If you're still stuck, I can try to offer some help for NPM & Node usage, but if you're going to be using something niche like Deno, know that you're going off the beaten path.
